basic:
  label: 基础设置
  items:
    small_title:
      name: small_title
      label: 网站副标题
      type: text
      placeholder: '网站副标题'
    navbar_top:
      name: navbar_top
      label: 导航栏固定
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    background_pc:
      name: background_pc
      label: PC端博客背景图
      type: attachment
      placeholder: 'PC端博客背景图'
      default: 'https://api.btstu.cn/sjbz/?lx=dongman&format=images&method=pc'
    background_mobile:
      name: background_mobile
      label: 移动端博客背景图
      type: attachment
      placeholder: '移动端博客背景图'
      default: 'https://api.btstu.cn/sjbz/?lx=dongman&format=images&method=mobile'
    link_comment_id:
      name: link_comment_id
      label: 友链界面评论区ID
      type: text
      default: 2
      placeholder: '友链界面评论区ID'
      description: '友链界面没有ID，需要指定一个自定义页面的ID用于评论，被指定的文章评论区将作为友链的评论区。不存在的ID将导致评论功能无法使用，不建议随便修改。'
    record_number:
      name: record_number
      label: 备案号
      type: text
      placeholder: '工信部备案号'
    record_number_ps:
      name: record_number_ps
      label: 公安部备案
      type: text
      placeholder: '公安部备案号'
    website_time:
      name: website_time
      label: 建站时间
      type: text
      placeholder: 'YYYY/MM/dd HH:mm:ss'
    busuanzi:
      name: busuanzi
      label: busuanzi访客统计
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    night_logo:
      name: night_logo
      label: 黑夜模式的logo(放空默认为网站logo)
      type: attachment
      placeholder: '黑夜模式的logo'
post:
  label: 文章设置
  items:
    mathjax_enable:
      name: mathjax_enable
      label: MathJax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: atom-one-light
      options:
        - value: a11y-dark
          label: A11y Dark
        - value: a11y-light
          label: A11y Light
        - value: agate
          label: Agate
        - value: an-old-hope
          label: An Old Hope
        - value: androidstudio
          label: Androidstudio
        - value: arduino-light
          label: Arduino Light
        - value: arta
          label: Arta
        - value: ascetic
          label: Ascetic
        - value: atom-one-dark
          label: Atom One Dark
        - value: atom-one-dark-reasonable
          label: Atom One Dark Reasonable
        - value: atom-one-light
          label: Atom One Light
        - value: brown-paper
          label: Brown Paper
        - value: brown-papersq
          label: Brown Papersq
        - value: codepen-embed
          label: Codepen Embed
        - value: color-brewer
          label: Color Brewer
        - value: dark
          label: Dark
        - value: default
          label: Default
        - value: devibeans
          label: Devibeans
        - value: docco
          label: Docco
        - value: far
          label: Far
        - value: foundation
          label: Foundation
        - value: github-dark-dimmed
          label: Github Dark Dimmed
        - value: github-dark
          label: Github Dark
        - value: github
          label: Github
        - value: gml
          label: Gml
        - value: googlecode
          label: Googlecode
        - value: gradient-dark
          label: Gradient Dark
        - value: gradient-light
          label: Gradient Light
        - value: grayscale
          label: Grayscale
        - value: hybrid
          label: Hybrid
        - value: idea
          label: Idea
        - value: ir-black
          label: Ir Black
        - value: isbl-editor-dark
          label: Isbl Editor Dark
        - value: isbl-editor-light
          label: Isbl Editor Light
        - value: kimbie-dark
          label: Kimbie Dark
        - value: kimbie-light
          label: Kimbie Light
        - value: lightfair
          label: Lightfair
        - value: lioshi
          label: Lioshi
        - value: magula
          label: Magula
        - value: mono-blue
          label: Mono Blue
        - value: monokai-sublime
          label: Monokai Sublime
        - value: monokai
          label: Monokai
        - value: night-owl
          label: Night Owl
        - value: nnfx-dark
          label: Nnfx dark
        - value: nnfx-light
          label: Nnfx Light
        - value: nord
          label: Nord
        - value: obsidian
          label: Obsidian
        - value: paraiso-dark
          label: Paraiso Dark
        - value: paraiso-light
          label: Paraiso Light
        - value: pojoaque
          label: Pojoaque
        - value: purebasic
          label: Purebasic
        - value: qtcreator-dark
          label: Qtcreator Dark
        - value: qtcreator-light
          label: Qtcreator Light
        - value: rainbow
          label: Rainbow
        - value: routeros
          label: Routeros
        - value: school-book
          label: School Book
        - value: shades-of-purple
          label: Shades Of Purple
        - value: srcery
          label: Srcery
        - value: stackoverflow-dark
          label: Stackoverflow Dark
        - value: stackoverflow-light
          label: Stackoverflow Light
        - value: sunburst
          label: Sunburst
        - value: tomorrow-night-blue
          label: Tomorrow Night Blue
        - value: tomorrow-night-bright
          label: Tomorrow Night Bright
        - value: vs
          label: Vs
        - value: vs2015
          label: Vs 2015
        - value: xcode
          label: Xcode
        - value: xt256
          label: Xt 256
    article_end:
      name: article_end
      label: 阅读结束文字
      type: text
      placeholder: '阅读结束的提示文字'
    copyright:
      name: copyright
      label: 文章底部版权声明
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    share_type:
      name: share_type
      label: 文章分享组件
      type: select
      default: ''
      options:
        - value: ''
          label: '无'
        - value: addtoany
          label: addtoany
        - value: bdshare
          label: bdshare
        - value: sharejs
          label: sharejs
    donate_alipay:
      name: donate_alipay
      label: 支付宝捐赠二维码
      type: attachment
      placeholder: '二维码地址'
    donate_wechat:
      name: donate_wechat
      label: 微信捐赠二维码
      type: attachment
      placeholder: '二维码地址'
sidebar:
  label: 侧边栏
  items:
    left_sidebar_sticky:
      name: left_sidebar_sticky
      label: 左侧边栏悬浮
      type: select
      default: bottom
      options:
        - value: top
          label: 固定顶部
        - value: bottom
          label: 固定底部
        - value: none
          label: 不悬浮
    right_sidebar_sticky:
      name: right_sidebar_sticky
      label: 右侧边栏悬浮
      type: select
      default: top
      options:
        - value: top
          label: 固定顶部
        - value: bottom
          label: 固定底部
        - value: none
          label: 不悬浮
    notice_content:
      name: notice_content
      label: 博客公告
      type: textarea
      placeholder: 请输入公告内容（html格式）
    profile_avatar_type:
      name: profile_avatar_type
      label: 头像形状
      type: select
      default: 'avatar_rounded'
      options:
        - value: avatar_rounded
          label: '圆形'
        - value: avatar_square
          label: '方形'
    color_character:
      name: color_character
      label: 彩字内容
      type: textarea
      placeholder: 彩字内容（'','',...）
    profile_location:
      name: profile_location
      label: 地理位置
      type: text
      placeholder: '个人所在地'
    profile_follow_url:
      name: profile_follow_url
      label: (关注我)按钮地址
      type: text
      placeholder: '默认为博客地址'
    social_github:
      name: social_github
      label: Github
      type: text
      placeholder: 'Github 用户名'
    social_qq:
      name: social_qq
      label: QQ
      type: text
      placeholder: 'QQ 号'
    social_weibo:
      name: social_weibo
      label: 微博
      type: text
      placeholder: '微博用户名'
    social_twitter:
      name: social_twitter
      label: Twitter
      type: text
      placeholder: 'Twitter 用户名'
    social_facebook:
      name: social_facebook
      label: Facebook
      type: text
      placeholder: 'Facebook 用户名'
    social_email:
      name: social_email
      label: '邮箱'
      type: text
      placeholder: '邮箱地址'
    social_telegram:
      name: social_telegram
      label: Telegram
      type: text
      placeholder: 'Telegram 用户名'
    social_csdn:
      name: social_csdn
      label: CSDN
      type: text
      placeholder: 'CSDN 主页'
    ad_content:
      name: ad_content
      label: 侧边栏广告代码
      type: textarea
      placeholder: '在这里黏贴广告联盟提供的广告代码'
    sidebar_profile:
      name: sidebar_profile
      label: 侧边栏个人资料
      type: radio
      default: left
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_toc:
      name: sidebar_toc
      label: 侧边栏目录
      type: radio
      default: right
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_notice:
      name: sidebar_notice
      label: 侧边栏公告
      type: radio
      default: right
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    ad_piece:
      name: ad_piece
      label: 侧边栏广告
      type: radio
      default: none
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_recentpost:
      name: sidebar_recentpost
      label: 侧边栏最近文章
      type: radio
      default: right
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_recentcomment:
      name: sidebar_recentcomment
      label: 侧边栏最近评论
      type: radio
      default: right
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_categories:
      name: sidebar_categories
      label: 侧边栏分类
      type: radio
      default: left
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_tags:
      name: sidebar_tags
      label: 侧边栏标签
      type: radio
      default: left
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_tagcloud:
      name: sidebar_tagcloud
      label: 侧边栏标签云
      type: radio
      default: none
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
    sidebar_links:
      name: sidebar_links
      label: 侧边栏链接
      type: radio
      default: left
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
        - value: none
          label: 关闭
page:
  label: 页面设置
  items:
    links_thumbnail:
      name: links_thumbnail
      label: 友链界面缩略图
      type: attachment
      placeholder: '友链界面缩略图'
    links_default_avatar:
      name: links_default_avatar
      label: 友链界面默认头像
      type: attachment
      placeholder: '未设置头像用户的默认头像'
    links_blogger_avatar:
      name: links_blogger_avatar
      label: 友链界面博主头像链接
      type: attachment
      placeholder: '博主头像链接'
    links_info:
      name: links_info
      label: 友链界面补充信息
      type: textarea
      placeholder: '友链界面补充信息'
      default: "添加友链后按以上格式在本帖留言即可，留言后看到会立即添加友链，一般和同样的博客类网站交换。"
custom_links:
  label: 自定义链接
  items:
    links_top:
      name: links_top
      label: 顶部链接
      type: textarea
      default: '<a class="navbar-item" target="_blank" title="我的GitHub" href="https://github.com/nineya">
                    <i class="fab fa-github"></i>
                </a>'
    links_footer:
      name: links_footer
      label: 底部链接
      type: textarea
      default: '<p class="control">
                    <a class="button is-white is-large" target="_blank" title="Creative Commons" href="https://creativecommons.org/">
                        <i class="fab fa-creative-commons"></i>
                    </a>
                </p>
                <p class="control">
                    <a class="button is-white is-large" target="_blank" title="Attribution 4.0 International" href="https://creativecommons.org/licenses/by/4.0/">
                        <i class="fab fa-creative-commons-by"></i>
                    </a>
                </p>'
other:
  label: 其他设置
  items:
    search_snow:
      name: search_snow
      label: 搜索框雪花背景
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sakura_fall:
      name: sakura_fall
      label: 樱花飘落
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    gallery_plus:
      name: gallery_plus
      label: 画廊功能增强
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d:
      name: live2d
      label: 看板娘
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    baidu_push:
      name: baidu_push
      label: 百度URL自动推送
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    toutiao_push:
      name: toutiao_push
      label: 头条搜索自动推送
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    seo360_push:
      name: seo360_push
      label: 360自动收录推送
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭